[scrolling]
# How many lines of scrollback to keep,
# '0' will disable scrolling.
history = 5000
multiplier = 3

[window]
  decorations = "None"
  [window.dimensions]
  lines = 90
  columns = 37


[font]
size = 18

  [font.normal]
  family = "MesloLGS NF"
  style = "Regular"

  [font.bold]
  family = "MesloLGS NF"
  style = "Bold"

  [font.italic]
  family = "MesloLGS NF"
  style = "Italic"

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"

[colors.normal]
black = "0x32302f"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.bright]
black = "0x32302f"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.cursor]
text = "#000000"
cursor = "#EEFFFF"

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001bf" }, # Move one word forward
    { key = "Left",  mods = "Alt", chars = "\u001bb" }  # Move one word backward
]

[mouse]
  hide_when_typing = true

# [[key_bindings]]
# key = "Insert"
# mods = "Shift"
# action = "PasteSelection"

# [[key_bindings]]
# key = "Insert"
# mods = "Control"
# action = "Copy"
