[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[scrolling]
# How many lines of scrollback to keep,
# '0' will disable scrolling.
history = 5000
multiplier = 3

[window]
  decorations = "None"
  [window.dimensions]
  lines = 90
  columns = 37


[font]
size = 18

  [font.normal]
  family = "MesloLGS Nerd Font"
  style = "Regular"

  [font.bold]
  family = "MesloLGS Nerd Font"
  style = "Bold"

  [font.italic]
  family = "MesloLGS Nerd Font"
  style = "Italic"

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001bf" }, # Move one word forward
    { key = "Left",  mods = "Alt", chars = "\u001bb" }  # Move one word backward
]

[mouse]
  hide_when_typing = true

# [[key_bindings]]
# key = "Insert"
# mods = "Shift"
# action = "PasteSelection"

# [[key_bindings]]
# key = "Insert"
# mods = "Control"
# action = "Copy"
