scrolling:
  # How many lines of scrollback to keep,
  # '0' will disable scrolling.
  history: 5000
  multiplier: 3

window:
  dimensions:
    lines: 90
    columns: 37
  decoration: none
  gtk_theme_variant: dark

font:
  size: 18
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic

colors:
  primary:
    background: "0x1d2021"
    foreground: "0xd4be98"
  normal:
    black: "0x32302f"
    red: "0xea6962"
    green: "0xa9b665"
    yellow: "0xd8a657"
    blue: "0x7daea3"
    magenta: "0xd3869b"
    cyan: "0x89b482"
    white: "0xd4be98"

  bright:
    black: "0x32302f"
    red: "0xea6962"
    green: "0xa9b665"
    yellow: "0xd8a657"
    blue: "0x7daea3"
    magenta: "0xd3869b"
    cyan: "0x89b482"
    white: "0xd4be98"

  cursor:
    text: "#000000"
    cursor: "#EEFFFF"

key_bindings:
  - key: Insert
    mods: Shift
    action: PasteSelection
  - key: Insert
    mods: Control
    action: Copy
